### ISSUE TITLE
Why is softbib citing itsself like this?

### ISSUE THREAD

**Issue by brueckmann** [vincentarelbundock/softbib#11]
Hello, 

Such a helpful package, thank you! 

However, I discovered an oddity in my bib file (and please excuse if this does not "warrant" an issue!)

```
@Article{softbib,
  title = {Software Citations in Political Science.},
  author = {Vincent Arel-Bundock and Joshua McCrain},
  journal = {PS: Political Science & Politics},
  year = {2023},
  volume = {April},
  pages = {1--4},
  doi = {10.1017/S1049096523000239},
}
```
I would have prefered it when the `&` was a `\&` instead because if not, I always get LaTex errors.

Also, I wonder, why the citation isn't the same as in the readme, where it can be found in the software bibliography example on LaTeX (reference [3]). 

My whole code for a reproducible example is: 

In R: 
```
library(softbib)
setwd("myworkingdirectorylink")
softbib::softbib(output = "software.bib")
```
And then I get the following bibfile: 

```
@Manual{base,
  title = {R: A Language and Environment for Statistical Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2024},
  url = {https://www.R-project.org/},
}

@Article{softbib,
  title = {Software Citations in Political Science.},
  author = {Vincent Arel-Bundock and Joshua McCrain},
  journal = {PS: Political Science & Politics},
  year = {2023},
  volume = {April},
  pages = {1--4},
  doi = {10.1017/S1049096523000239},
}
```
Maybe also of interest: 

```
> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.0

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] softbib_0.0.2 remotes_2.5.0

loaded via a namespace (and not attached):
 [1] desc_1.4.3        backports_1.5.0   R6_2.5.1          ps_1.7.6          cli_3.6.3        
 [6] processx_3.8.4    callr_3.7.6       renv_1.0.11       bibtex_0.5.1      compiler_4.4.0   
[11] rstudioapi_0.16.0 tools_4.4.0       pkgbuild_1.4.4    checkmate_2.3.2   curl_5.2.1       
```

Let me know, if you need anything more :)

**Comment by brueckmann** [comment]
Thanks, the ampersand is escaped after `install_github("vincentarelbundock/softbib")`.
However, somehow it didn't replace my file anymore, I had to manually delete it to get the new text in. That wasn't the case for me before. 

The latter point is more contentwise. In the [readme](https://github.com/vincentarelbundock/softbib/blob/main/README.md) there is a picture at the bottom, and this shows the citation for softbib like this: Arel-Bundock, V. (2022). softbib: Software Bibliographies for R Projects. R package version 0.0.1. However, now the citation for softbib is your PS article with Joshua McCrain. Not saying you are not free to create whatever citation you want for your packages, I just wanted to indicate this inconsistency and maybe a softbib1 (with software version) and a softbib2 (with journal article), as your packgae creates for some other papers, whould be highly appreciated by your users. 

Hope that clarifies things!

**Comment by vincentarelbundock** [comment]
Thanks again!
