### ISSUE TITLE
Add option to skip certain subdirectories

### ISSUE THREAD

**Issue by carlislerainey** [vincentarelbundock/softbib#8]
I usually have a subdirectory in my projects (e.g., `-old/`) where I drop files I no longer need. I would like to have `softbib()` skip this/these directories.

**Comment by vincentarelbundock** [comment]
You'll need to reinstall from Github and restart `R`, but the latest version should honor the instructions given to a `.renvignore` file in the working directory. See here:

https://github.com/vincentarelbundock/softbib#ignoring-files-and-folders

This is a bit convoluted, but I can't currently think of an easy way to add an argument directly to the `softbib()` function.
